language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

install:
  - pip install 'pipenv!=6.2.4'
  - pipenv install --dev --skip-lock

script:
  - pipenv run pytest

jobs:
  include:
    - stage: Lint
      python: "3.6"
      script: make lint
